# Install directory prefixes.
PREFIX_BIN=/app/bin
PREFIX_INCLUDE=/app/include
PREFIX_LIB=/app/lib
PREFIX_SHARE=/app/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-std=c++11


# FASTJET3 configuration.
FASTJET3_USE=true
FASTJET3_BIN=/app/bin/
FASTJET3_INCLUDE=/app/include
FASTJET3_LIB=/app/lib


# PYTHON configuration.
PYTHON_USE=true
PYTHON_BIN=/app/bin/
PYTHON_INCLUDE=/app/include/
PYTHON_LIB=/app/lib/
